name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SPRING_PROFILES_ACTIVE: test
        JWT_SECRET: qbXIuuEDkAoFP8TZsJGs70tuUscmlcNY90lYjZyA6RYffojPGCDvQ3fWiKscuZTBemOR7rOHkJM29aeoBStX6Ca94FZSm6K95C80NOXOKt9600j4YIaYMNtS3QrMfYJl4Eq0HfbzEmbzOD8cj3H5ddjZuM2JxQthlxL9IX5KQKfWp6mr[...]
        JWT_EXPIRATION: 3600000
        JWT_REFRESH_EXPIRATION: 86400000

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and test with Maven
      run: mvn -B test

    - name: Build package
      run: mvn -B package --file pom.xml -DskipTests

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
